### PR TITLE
JSON structure modifications

### PR DESCRIPTION
**Pull request by szul**
Server.py changes to modify the JSON structure in order to eliminate the need for front end alterations and the array extension (which were only meant to give a visual demo anyway).

### CODE REVIEW

**Comment by szul** [comment]
I've modified the tree.html to make requests to the server.py for more nodes if no children are present on the selected node. This appends the returned JSON to the original JSON structure, essentially creating the infinite drilling we talked about at the Open Hack. There are some issues that I will add to the issues tab once this pull request is merged, but below is the gist:

1.) With nodes that need a round trip to populate children, D3 sees them as empty, so the circle is unfilled until the round trip. The JSON needs to support some sort of "look ahead" property to see if return trips will have data, and adjust the fill appropriately.

2.) The data for contributors and contributors_url comes from the search query on the same level as each other, but it doesn't look like they are correlated. I assumed they matched positions with one another, and combined them into a childrens node, but some contributors don't seem to have URLs (hence the out of range exception without the range check). This could throw off the correlation of the combined values if a contributor early in the dataset has no URL.

3.) This graph is not conducive to infinite data. The canvas runs out of room quickly, so a lot of position manipulation would be needed to make this work well. Moving to the bubble view that we discussed at the Open Hack would be ideal.

**Comment by HarryRybacki-zz** [comment]
Very interesting. I'm sure we could work out something similar to pagination for deeper layers of children. Bryan Gorges, who was leading the data vis side, is still working on the bubble view as well. Although he has been told to focus on another task for the upcoming epic I have a feeling he's still working on the side. I'll add him so we can get his thoughts! This is unrelated but feel free to hang out in #cos on Freenode!

**Comment by szul** [comment]
Pagination would work, along with some data management. One thing I forgot to mention above is that by appending data to the JSON structure after server trips, the dataset and node lists will get large if somebody is continually drilling in. If you continued with this tree, you'd probably want to close other open nodes at the same hierarchy when a new node from that hierarchy is selected, and also remove the child nodes from the dataset for the closed nodes. This might push more heavy lifting onto the server, but it lessens the risk of larger, overwhelming data on the client end. Of course, I'm just guessing on this--a stress test would probably clarify more.

**Comment by Ghalko** [comment]
I think keeping a history of searches would be much lighter rather than appending the results. Maybe they can click on past nodes to re-search from that node with the stored search. This would also require pruning all but the most recent search and a linear history. Just an idea.

**Comment by szul** [comment]
Right. This is why I mentioned the original bubble visualization that we looked at during the Open Hack. It would be a much better representation of how the data is looking to be visualized/utilized.

**Comment by szul** [comment]
@Ghalko @HarryRybacki I was looking at my local files yesterday and noticed that they started throwing an exception. In debugging, I see that you guys are modifying the JSON returned from the search to be more hierarchical. Looking good.

I'm going to close this pull request since you're modify stuff on your end. I was using it as an opportunity to work with the hackathon files since I had to leave early that Saturday.

**Comment by Ghalko** [comment]
You can certainly keep contributing @szul, since it isn't a priority right now we need to work on other things.

**Comment by szul** [comment]
@Ghalko Yeah, I might take a look at that bubble diagram in the D3. I was playing around with the Chord diagram on a different project. It's definitely a great data visualization library.

**Pull request closed without merging**
